simple_bdd/code/config/routes.rb
Rails.application.routes.draw do
  resources :items do
    get :mark_completed, on: :member
  end
end

simple_bdd/code/app/models/item.rb
class Item < ActiveRecord::Base
end

simple_bdd/code/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

simple_bdd/code/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def create
    Item.create(item_params)
    redirect_to items_path
  end
 
  def mark_completed
    @item = Item.find(params[:id])
    @item.update_attributes(completed: true)
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:text)
  end 
end

simple_bdd/code/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_bdd/code/app/helpers/items_helper.rb
module ItemsHelper
  def completed?(item)
    if item.completed
      "Completed"
    else
      "Not Completed"
    end
  end
end

simple_bdd/code/app/views/items/index.html.erb
<div id="item-list">
  <% if @items.size > 0 %>
    <% @items.each do |item| %>
      <div id="item-<%= item.id %>" %>
        <%= item.text %> <%= completed?(item) %>
        <% unless item.completed %>
          <%= link_to "Mark Completed", mark_completed_item_path(item) %>
        <% end %>
      </div>
     <% end %>
   <% else %>
     No items in list
   <% end %>
</div>

<div id="new-item" %>
  <%= form_for :item do |f| %>
    <%= f.label :text %>:
    <%= f.text_field :text %>
    <%= f.submit %>
  <% end %>
</div>

simple_bdd/code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>